package main

// AUTOGENERATED FILE - DO NOT EDIT.
//
// This file has been automatically generated by FrankenPHP extension generator
// and should not be edited as it will be overwritten when running the
// extension generator again.
//
// You may edit the file and remove this comment if you plan to manually maintain
// this file going forward.

// #include <stdlib.h>
// #include "frankenphp_llm.h"
import "C"
import (
	_ "runtime/cgo"
	"unsafe"

	"github.com/dunglas/frankenphp"
)

func init() {
	frankenphp.RegisterExtension(unsafe.Pointer(&C.frankenphp_llm_module_entry))
}

//export go_frankenphp_llm_generate
func go_frankenphp_llm_generate(modelPath *C.zend_string,
	prompt *C.zend_string,
	maxTokens int64,
	strategy *C.zend_string,
	temperature float64,
	topK int64,
	topP float64,
	repeatPenalty float64,
	repeatLastN int64,
	systemPrompt *C.zend_string,
	template *C.zend_string,
	session *C.zend_string) unsafe.Pointer {
	return frankenphp_llm_generate(modelPath, prompt, maxTokens, strategy, temperature, topK, topP, repeatPenalty, repeatLastN, systemPrompt, template, session)
}

//export go_frankenphp_llm_generate_with_stats
func go_frankenphp_llm_generate_with_stats(modelPath *C.zend_string,
	prompt *C.zend_string,
	maxTokens int64,
	strategy *C.zend_string,
	temperature float64,
	topK int64,
	topP float64,
	repeatPenalty float64,
	repeatLastN int64,
	systemPrompt *C.zend_string,
	template *C.zend_string,
	session *C.zend_string) unsafe.Pointer {
	return frankenphp_llm_generate_with_stats(modelPath, prompt, maxTokens, strategy, temperature, topK, topP, repeatPenalty, repeatLastN, systemPrompt, template, session)
}

//export go_frankenphp_llm_clear_session
func go_frankenphp_llm_clear_session(modelPath *C.zend_string, session *C.zend_string) bool {
	return frankenphp_llm_clear_session(modelPath, session)
}
