<?php

/** @generate-class-entries */

// AUTOGENERATED FILE - DO NOT EDIT.
//
// This file has been automatically generated by FrankenPHP extension generator
// and should not be edited as it will be overwritten when running the
// extension generator again.
//
// You may edit the file and remove this comment if you plan to manually maintain
// this file going forward.

function frankenphp_llm_generate(string $modelPath, string $prompt, int $maxTokens = 100, string $strategy = "greedy", float $temperature = 1.0, int $topK = 50, float $topP = 0.9, float $repeatPenalty = 1.15, int $repeatLastN = 64, string $systemPrompt = "", string $template = "", string $session = ""): string {}

function frankenphp_llm_generate_with_stats(string $modelPath, string $prompt, int $maxTokens = 100, string $strategy = "greedy", float $temperature = 1.0, int $topK = 50, float $topP = 0.9, float $repeatPenalty = 1.15, int $repeatLastN = 64, string $systemPrompt = "", string $template = "", string $session = ""): string {}

function frankenphp_llm_clear_session(string $modelPath, string $session): bool {}


