// AUTOGENERATED FILE - DO NOT EDIT.
//
// This file has been automatically generated by FrankenPHP extension generator
// and should not be edited as it will be overwritten when running the
// extension generator again.
//
// You may edit the file and remove this comment if you plan to manually maintain
// this file going forward.

#include <php.h>
#include <Zend/zend_API.h>
#include <Zend/zend_hash.h>
#include <Zend/zend_types.h>
#include <stddef.h>

#include "frankenphp_llm.h"
#include "frankenphp_llm_arginfo.h"
#include "_cgo_export.h"


PHP_MINIT_FUNCTION(frankenphp_llm) {
    
    return SUCCESS;
}

zend_module_entry frankenphp_llm_module_entry = {STANDARD_MODULE_HEADER,
                                         "frankenphp_llm",
                                         ext_functions,             /* Functions */
                                         PHP_MINIT(frankenphp_llm),  /* MINIT */
                                         NULL,                      /* MSHUTDOWN */
                                         NULL,                      /* RINIT */
                                         NULL,                      /* RSHUTDOWN */
                                         NULL,                      /* MINFO */
                                         "1.0.0",                   /* Version */
                                         STANDARD_MODULE_PROPERTIES};
PHP_FUNCTION(frankenphp_llm_generate)
{
    zend_string *modelPath = NULL;
    zend_string *prompt = NULL;
    zend_long maxTokens = 100;
    zend_string *strategy = NULL;
    double temperature = 1.0;
    zend_long topK = 50;
    double topP = 0.9;
    double repeatPenalty = 1.15;
    zend_long repeatLastN = 64;
    zend_string *systemPrompt = NULL;
    zend_string *template = NULL;
    zend_string *session = NULL;
    ZEND_PARSE_PARAMETERS_START(2, 12)
        Z_PARAM_STR(modelPath)
        Z_PARAM_STR(prompt)
        Z_PARAM_OPTIONAL
        Z_PARAM_LONG(maxTokens)
        Z_PARAM_STR(strategy)
        Z_PARAM_DOUBLE(temperature)
        Z_PARAM_LONG(topK)
        Z_PARAM_DOUBLE(topP)
        Z_PARAM_DOUBLE(repeatPenalty)
        Z_PARAM_LONG(repeatLastN)
        Z_PARAM_STR(systemPrompt)
        Z_PARAM_STR(template)
        Z_PARAM_STR(session)
    ZEND_PARSE_PARAMETERS_END();
    zend_string *result = go_frankenphp_llm_generate(modelPath, prompt, (long) maxTokens, strategy, (double) temperature, (long) topK, (double) topP, (double) repeatPenalty, (long) repeatLastN, systemPrompt, template, session);
    if (result) {
        RETURN_STR(result);
    }

	RETURN_EMPTY_STRING();
}

PHP_FUNCTION(frankenphp_llm_generate_with_stats)
{
    zend_string *modelPath = NULL;
    zend_string *prompt = NULL;
    zend_long maxTokens = 100;
    zend_string *strategy = NULL;
    double temperature = 1.0;
    zend_long topK = 50;
    double topP = 0.9;
    double repeatPenalty = 1.15;
    zend_long repeatLastN = 64;
    zend_string *systemPrompt = NULL;
    zend_string *template = NULL;
    zend_string *session = NULL;
    ZEND_PARSE_PARAMETERS_START(2, 12)
        Z_PARAM_STR(modelPath)
        Z_PARAM_STR(prompt)
        Z_PARAM_OPTIONAL
        Z_PARAM_LONG(maxTokens)
        Z_PARAM_STR(strategy)
        Z_PARAM_DOUBLE(temperature)
        Z_PARAM_LONG(topK)
        Z_PARAM_DOUBLE(topP)
        Z_PARAM_DOUBLE(repeatPenalty)
        Z_PARAM_LONG(repeatLastN)
        Z_PARAM_STR(systemPrompt)
        Z_PARAM_STR(template)
        Z_PARAM_STR(session)
    ZEND_PARSE_PARAMETERS_END();
    zend_string *result = go_frankenphp_llm_generate_with_stats(modelPath, prompt, (long) maxTokens, strategy, (double) temperature, (long) topK, (double) topP, (double) repeatPenalty, (long) repeatLastN, systemPrompt, template, session);
    if (result) {
        RETURN_STR(result);
    }

	RETURN_EMPTY_STRING();
}

PHP_FUNCTION(frankenphp_llm_clear_session)
{
    zend_string *modelPath = NULL;
    zend_string *session = NULL;
    ZEND_PARSE_PARAMETERS_START(2, 2)
        Z_PARAM_STR(modelPath)
        Z_PARAM_STR(session)
    ZEND_PARSE_PARAMETERS_END();
    int result = go_frankenphp_llm_clear_session(modelPath, session);
    RETURN_BOOL(result);
}

